name: cfn-lint-oliwer
version: 0.44.3
summary: CloudFormation template checker
description: |
  CloudFormation template checker for syntax and best practices.
license: Apache-2.0
base: core18

grade: stable
confinement: strict

parts:
  cfn-lint:
    plugin: python
    python-version: python3
    python-packages:
      - cfn-lint

apps:
  cfn-lint-oliwer:
    command: bin/cfn-lint
    plugs:
      - home

