name: AutoUpdate

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Look for new upstream release and update snapcraft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        set -euxo pipefail

        upstream=$(curl -fsSL "https://api.github.com/repos/aws-cloudformation/cfn-python-lint/releases/latest" \
          | jq -r .tag_name | tr -d v)
        test -n "$upstream"

        git clone --depth=1 "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" .

        current=$(awk '/^version:/{print $2}' snapcraft.yaml)
        test -n "$current"

        [ "$current" != "$upstream" ] || exit 0

        sed -i "s/^version: .*\$/version: $upstream/" snapcraft.yaml

        git config --local user.name ${GITHUB_ACTOR}
        git config --local user.email ${GITHUB_ACTOR}@github.com

        git commit -a -m "$upstream"
        git push

