name: AutoUpdate

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Look for new upstream release and create new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        set -euxo pipefail

        upstream=$(curl -sS "https://api.github.com/repos/aws-cloudformation/cfn-python-lint/releases/latest" \
          | jq -r .tag_name | tr -d v)
        test -n "$upstream"

        git clone "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" .

        current=$(git describe)
        test -n "$current"

        [ "$current" != "$upstream" ] || exit 0

        git config --local user.name ${GITHUB_ACTOR}
        git config --local user.email ${GITHUB_ACTOR}@github.com

        git tag -a "$upstream" -m "$upstream"
        git push --tags
