name: AutoUpdate

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  plop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Sync releases with upstream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        set -euxo pipefail
        upstreamVer=$(curl -sS "https://api.github.com/repos/aws-cloudformation/cfn-python-lint/releases/latest" \
          | jq -r .tag_name | tr -d v)
        test -n "$upstreamVer"
        if [ "$(git describe)" != "$upstreamVer" ]; then
          curl -sS -X POST "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" \
            -H "Authorization: token $GITHUB_TOKEN" -d @- <<__
            { "name":"$upstreamVer", "tag_name":"$upstreamVer" } 
        __
        fi

