name: AutoUpdate

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  plop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Look for new upstream release and create new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        set -euxo pipefail
        upstreamVer=$(curl -sS "https://api.github.com/repos/aws-cloudformation/cfn-python-lint/releases/latest" \
          | jq -r .tag_name | tr -d v)
        test -n "$upstreamVer"
        if [ "$(git describe)" != "$upstreamVer" ]; then
          echo "New upstream release: $upstreamVer"
          curl -sS -X POST "https://api.github.com/repos/$GITHUB_REPOSITORY/git/tags" \
            -H "Authorization: token $GITHUB_TOKEN" -d @- <<__
            { "tag":"$upstreamVer", "message":"$upstreamVer", "object:"$(git rev-parse HEAD)", "type":"commit" } 
        __
        else
          echo "No new release available."
        fi
        

